package ua.com.fielden.platform.entity.query.fluent.enums;

public enum Functions {
    ADD_DATE_INTERVAL,
    COUNT_DATE_INTERVAL,
    CONCAT,
    CASE_WHEN,
    ROUND,
    IF_NULL,
    UPPERCASE,
    LOWERCASE,
    NOW,
    SECOND,
    MINUTE,
    HOUR,
    DAY,
    MONTH,
    YEAR,
    DAY_OF_WEEK,
    DATE,
    ABS,
    SUM,
    MAX,
    MIN,
    COUNT,
    AVERAGE,
    SUM_DISTINCT,
    COUNT_DISTINCT,
    AVERAGE_DISTINCT,
    COUNT_ALL;
}
