CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B6CA7902_C679_498A_953C_99179B3CB148 START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0372D021_C7A2_4EF4_8F5C_67A609EF21F9 START WITH 2 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.NUMBERS(
    _ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0372D021_C7A2_4EF4_8F5C_67A609EF21F9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0372D021_C7A2_4EF4_8F5C_67A609EF21F9,
    _VERSION INT DEFAULT 0 NOT NULL,
    NUMBKEY VARCHAR(255),
    WONOINC VARCHAR(255)
);

CREATE CACHED TABLE PUBLIC.UNIQUE_ID(
    _ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B6CA7902_C679_498A_953C_99179B3CB148) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B6CA7902_C679_498A_953C_99179B3CB148,
    NEXT_VALUE INT
);


CREATE TABLE INSPECTED_ENTITIES
(
	_ID INT NOT NULL IDENTITY PRIMARY KEY,
	_VERSION INT NOT NULL DEFAULT 0,
	KEY_ VARCHAR(20) NOT NULL,
	DESC_ VARCHAR(255),
	INT_PROPERTY INT,
	DECIMAL_PROPERTY NUMERIC,
	MONEY_PROPERTY_AMOUNT NUMERIC,
	MONEY_PROPERTY_CURRENCY VARCHAR(3),
	DATE_PROPERTY TIMESTAMP,
	BOOLEAN_PROPERTY CHAR(1) NOT NULL DEFAULT 'Y',
	ENTITY_PROPERTY_ONE INT,
	ENTITY_PROPERTY_TWO INT
);

CREATE TABLE CRAFT(
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(32),
    DESC_ VARCHAR(255),
    RATE NUMERIC(18, 2),
    OVERTIME_RATE NUMERIC(18, 2),
    CT_MAINTSUPERVISOR CHAR(1),
    CT_ORIGINATOR CHAR(1),
    CT_AUTHORISOR CHAR(1),
    CT_ISSUER CHAR(1),
    CT_BUYER CHAR(1),
    CT_PLANNER CHAR(1),
    USER_ INT
);

CREATE TABLE USER_ (
    _ID INT NOT NULL PRIMARY KEY,
    _VERSION INT NOT NULL DEFAULT 0,
    KEY_ VARCHAR(255),
    PASSWORD_ VARCHAR(255) NOT NULL,
    BASE_ CHAR(1) NOT NULL,
    BASEDONUSER_ INT,
    EMAIL_ VARCHAR(255),
    RESETUUID_ VARCHAR(42),
    SALT_ VARCHAR(32),
    ACTIVE_FLAG_ CHAR(1) NOT NULL DEFAULT 'N',
    REFCOUNT_ INT NOT NULL DEFAULT 0,
    CREATEDBY_ INT,
    CREATEDDATE_ TIMESTAMP,
    CREATEDTRANSACTIONGUID_ CHAR(60),
    LASTUPDATEDBY_ INT,
    LASTUPDATEDDATE_ TIMESTAMP,
    LASTUPDATEDTRANSACTIONGUID_ CHAR(60)
);

CREATE TABLE USER_ROLE(
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(32),
    DESC_ VARCHAR(255),
    ACTIVE_FLAG_ CHAR(1) NOT NULL DEFAULT 'N',
    REFCOUNT_ INT NOT NULL DEFAULT 0,
    CREATEDBY_ INT,
    CREATEDDATE_ TIMESTAMP,
    CREATEDTRANSACTIONGUID_ CHAR(60),
    LASTUPDATEDBY_ INT,
    LASTUPDATEDDATE_ TIMESTAMP,
    LASTUPDATEDTRANSACTIONGUID_ CHAR(60)
);

CREATE TABLE USER_ROLE_ASSOCIATION(
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    ID_CRAFT INT NOT NULL,
    ID_USER_ROLE INT NOT NULL
);

CREATE TABLE SECURITY_ROLE_ASSOCIATION(
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    ID_USER_ROLE INT NOT NULL
);

CREATE TABLE ATTACHMENTS(
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(128),
    DESC_ VARCHAR(255)
);

CREATE TABLE TGVEHICLEMAKE_ (
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(128),
    DESC_ VARCHAR(255)
);

CREATE TABLE TGVEHICLEMODEL_ (
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(128),
    DESC_ VARCHAR(255),
    MAKE_ INT
);

CREATE TABLE TGVEHICLE_ (
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
    KEY_ VARCHAR(128),
    DESC_ VARCHAR(255),
    MODEL_ INT,
    PRICE_ NUMERIC(12,4)
);

CREATE TABLE TGFUELUSAGE_ (
    _ID INT NOT NULL,
    _VERSION INT DEFAULT 0 NOT NULL,
	VEHICLE_ INT,
	DATE_ TIMESTAMP,
	QTY_ NUMERIC(12,4)
)