package ua.com.fielden.platform.domain;

import ua.com.fielden.platform.attachment.Attachment;
import ua.com.fielden.platform.attachment.AttachmentPreviewEntityAction;
import ua.com.fielden.platform.attachment.AttachmentUploader;
import ua.com.fielden.platform.attachment.AttachmentsUploadAction;
import ua.com.fielden.platform.dashboard.DashboardRefreshFrequency;
import ua.com.fielden.platform.dashboard.DashboardRefreshFrequencyUnit;
import ua.com.fielden.platform.domain.metadata.*;
import ua.com.fielden.platform.entity.*;
import ua.com.fielden.platform.entity.functional.centre.CentreContextHolder;
import ua.com.fielden.platform.entity.functional.centre.SavingInfoHolder;
import ua.com.fielden.platform.entity.functional.master.AcknowledgeWarnings;
import ua.com.fielden.platform.entity.functional.master.PropertyWarning;
import ua.com.fielden.platform.keygen.KeyNumber;
import ua.com.fielden.platform.master.MasterInfo;
import ua.com.fielden.platform.menu.*;
import ua.com.fielden.platform.ref_hierarchy.*;
import ua.com.fielden.platform.security.session.UserSession;
import ua.com.fielden.platform.security.user.*;
import ua.com.fielden.platform.security.user.locator.UserLocator;
import ua.com.fielden.platform.security.user.master.menu.actions.UserMaster_OpenMain_MenuItem;
import ua.com.fielden.platform.security.user.master.menu.actions.UserMaster_OpenUserAndRoleAssociation_MenuItem;
import ua.com.fielden.platform.security.user.ui_actions.OpenUserMasterAction;
import ua.com.fielden.platform.share.ShareAction;
import ua.com.fielden.platform.tiny.TinyHyperlink;
import ua.com.fielden.platform.ui.config.*;
import ua.com.fielden.platform.web.centre.*;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

public class PlatformDomainTypes {
    public static final List<Class<? extends AbstractEntity<?>>> types = new ArrayList<>();
    public static final Set<Class<? extends AbstractEntity<?>>> typesDependentOnWebUI = new LinkedHashSet<>();
    public static final Set<Class<? extends AbstractEntity<?>>> typesNotDependentOnWebUI = new LinkedHashSet<>();

    static {
        types.add(MainMenuItem.class);
        types.add(User.class);
        types.add(ReUser.class);
        types.add(UserLocator.class);
        types.add(UserSecret.class);
        types.add(UserSession.class);
        types.add(UserRole.class);
        types.add(CopyUserRoleAction.class);
        types.add(SecurityTokenInfo.class);

        types.add(CentreConfigUpdater.class);
        types.add(CustomisableColumn.class);
        types.add(CentreColumnWidthConfigUpdater.class);
        types.add(CentrePreferredViewUpdater.class);
        types.add(CentreConfigShareAction.class);
        types.add(CentreConfigNewAction.class);
        types.add(CentreConfigDuplicateAction.class);
        types.add(CentreConfigLoadAction.class);
        types.add(CentreConfigEditAction.class);
        types.add(CentreConfigDeleteAction.class);
        types.add(CentreConfigSaveAction.class);
        types.add(LoadableCentreConfig.class);
        types.add(OverrideCentreConfig.class);
        types.add(CentreConfigConfigureAction.class);
        types.add(DashboardRefreshFrequencyUnit.class);
        types.add(DashboardRefreshFrequency.class);

        types.add(UserAndRoleAssociation.class);
        types.add(SynUserAndRoleAssociationActive.class);
        types.add(SynUserAndRoleAssociationInactive.class);
        types.add(SecurityRoleAssociation.class);
        types.add(EntityCentreConfig.class);
        types.add(EntityCentreAnalysisConfig.class);
        types.add(EntityMasterConfig.class);
        types.add(EntityLocatorConfig.class);
        types.add(Attachment.class);
        types.add(AttachmentUploader.class);
        types.add(AttachmentsUploadAction.class);
        types.add(TinyHyperlink.class);
        types.add(ShareAction.class);
        types.add(KeyNumber.class);
        types.add(CentreContextHolder.class);
        types.add(SavingInfoHolder.class);
        types.add(EntityNewAction.class);
        types.add(EntityEditAction.class);
        types.add(EntityDeleteAction.class);
        types.add(EntityExportAction.class);
        types.add(AcknowledgeWarnings.class);
        types.add(PropertyWarning.class);
        types.add(ModuleMenuItem.class);
        types.add(EntityCentreView.class);
        types.add(View.class);
        types.add(CustomView.class);
        types.add(ModuleMenu.class);
        types.add(Menu.class);
        types.add(EntityMasterView.class);
        types.add(MenuSaveAction.class);
        types.add(WebMenuItemInvisibility.class);
        types.add(SecurityMatrixInsertionPoint.class);
        types.add(SecurityTokenTreeNodeEntity.class);
        types.add(SecurityMatrixSaveAction.class);
        types.add(AttachmentPreviewEntityAction.class);
        types.add(MasterInfo.class);
        types.add(ReferenceHierarchy.class);
        types.add(ReferenceHierarchyEntry.class);
        types.add(TypeLevelHierarchyEntry.class);
        types.add(ReferencedByLevelHierarchyEntry.class);
        types.add(ReferenceLevelHierarchyEntry.class);
        types.add(Action.class);
        types.add(DomainType.class);
        types.add(DomainProperty.class);
        types.add(DomainPropertyHolder.class);
        types.add(DomainExplorer.class);
        types.add(DomainExplorerInsertionPoint.class);
        types.add(DomainTreeEntity.class);
        types.add(DomainPropertyTreeEntity.class);
        types.add(UserMenuVisibilityAssociator.class);
        types.add(OpenUserMasterAction.class);
        types.add(UserMaster_OpenMain_MenuItem.class);
        types.add(UserMaster_OpenUserAndRoleAssociation_MenuItem.class);
        types.add(UserDefinableHelp.class);
        types.add(PersistentEntityInfo.class);
        types.add(ApplicationConfig.class);

        typesDependentOnWebUI.add(EntityExportAction.class);
        typesDependentOnWebUI.add(CentreConfigUpdater.class);
        typesDependentOnWebUI.add(CentreConfigLoadAction.class);
        typesDependentOnWebUI.add(CentreConfigEditAction.class);
        typesDependentOnWebUI.add(CentreConfigSaveAction.class);
        typesDependentOnWebUI.add(CentreConfigConfigureAction.class);

        typesNotDependentOnWebUI.addAll(types);
        typesNotDependentOnWebUI.removeAll(typesDependentOnWebUI);
    }
}
