CREATE TABLE MAKE (
   MAKE varchar(10) PRIMARY KEY,
   MAKE_DESC varchar(255)
);

INSERT INTO MAKE VALUES('MAKE1', 'DESC1');
INSERT INTO MAKE VALUES('MAKE2', 'DESC2');
INSERT INTO MAKE VALUES('MAKE3', 'DESC3');
INSERT INTO MAKE VALUES('MAKE4', 'DESC4');

CREATE TABLE MODEL (
   MODEL varchar(20),
   MODEL_DESC varchar(200),
   MAKE varchar(10)
);

INSERT INTO MODEL VALUES('MODEL1', 'DESC1', 'MAKE1');
INSERT INTO MODEL VALUES('MODEL2', 'DESC2', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL3', 'DESC3', null);
INSERT INTO MODEL VALUES('MODEL4', 'DESC1', 'MAKE4');
INSERT INTO MODEL VALUES('MODEL5', 'DESC2', 'MAKE1');
INSERT INTO MODEL VALUES('MODEL6', 'DESC3', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL7', 'DESC1', 'MAKE1');
INSERT INTO MODEL VALUES('MODEL8', 'DESC2', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL9', 'DESC3', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL10', 'DESC1', 'MAKE1');
INSERT INTO MODEL VALUES('MODEL11', 'DESC2', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL12', 'DESC3', 'MAKE3');
INSERT INTO MODEL VALUES('MODEL13', 'DESC1', 'MAKE1');
INSERT INTO MODEL VALUES('MODEL14', 'DESC2', 'MAKE2');
INSERT INTO MODEL VALUES('MODEL15', 'DESC3', 'MAKE4');

CREATE TABLE FUEL_USAGE (
   ID_COLUMN INT NOT NULL PRIMARY KEY,
   EQUIPNO varchar(10),
   USAGE_DATE datetime,
   FUEL_TYPE varchar(4)
);

INSERT INTO FUEL_USAGE VALUES (1, 'MERS', '2009-11-04 15:13:00', 'D');
INSERT INTO FUEL_USAGE VALUES (2, 'MERS', '2008-10-14 00:00:00', 'U');

CREATE TABLE METER_READING (
   ID_COLUMN INT NOT NULL PRIMARY KEY,
   EQUIPNO VARCHAR(10),
   LAST_READING_DATE datetime,
   LAST_READING NUMERIC(18,2),
   WONO VARCHAR(8),
   FUEL_USAGE_ID INT
);

INSERT INTO METER_READING VALUES(1, 'MERS', '2009-11-04 15:13:00', 24000, NULL, 1);
INSERT INTO METER_READING VALUES(2, 'MERS', '2009-11-05 12:00:00', 24500, NULL, NULL);

COMMIT;

CREATE TABLE ALL_WORK_ORDERS (
   EQUIPNO VARCHAR(10),
   ACTUAL_START datetime,
   METER_READING NUMERIC(18,2),
   WONO VARCHAR(8)
);
