/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   iron-list.js
 */

import {IronResizableBehavior} from '@polymer/iron-resizable-behavior/iron-resizable-behavior.js';

import {IronScrollTargetBehavior} from '@polymer/iron-scroll-target-behavior/iron-scroll-target-behavior.js';

import {OptionalMutableDataBehavior as OptionalMutableDataBehavior$0} from '@polymer/polymer/lib/legacy/mutable-data-behavior.js';

import {Polymer as Polymer$0} from '@polymer/polymer/lib/legacy/polymer-fn.js';

import {dom, flush as flush$0} from '@polymer/polymer/lib/legacy/polymer.dom.js';

import {Templatizer} from '@polymer/polymer/lib/legacy/templatizer-behavior.js';

import {animationFrame, idlePeriod, microTask} from '@polymer/polymer/lib/utils/async.js';

import {Debouncer} from '@polymer/polymer/lib/utils/debounce.js';

import {enqueueDebouncer, flush} from '@polymer/polymer/lib/utils/flush.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {matches, translate} from '@polymer/polymer/lib/utils/path.js';

declare namespace Polymer {

  interface OptionalMutableDataBehavior {
  }

  const OptionalMutableDataBehavior: object;
}
