BEGIN TRANSACTION transactio

/* DEKTOP: check */
SELECT
    CONCAT(MAX(SUBSTRING(TITLE, 1, 15)), '[', SUBSTRING(TITLE, 17, 100)) AS TITLE_TO_DELETE,
    (SELECT KEY_ FROM USER_ U WHERE U._ID = ID_CRAFT) AS OWNER,
    (SELECT KEY_ FROM MAIN_MENU M WHERE M._ID = ID_MAIN_MENU) AS MI_TYPE
FROM ENTITY_CENTRE_CONFIG
WHERE
    TITLE LIKE '__________SAVED[[]%'
    OR TITLE LIKE '__________FRESH[[]%'
GROUP BY
    ID_MAIN_MENU,
    ID_CRAFT,
    SUBSTRING(TITLE, 17, 100)
HAVING
    COUNT(SUBSTRING(TITLE, 1, 15)) < 2
    AND MAX(SUBSTRING(TITLE, 1, 15)) = '__________SAVED'

/* DESKTOP: delete */
DELETE
FROM ENTITY_CENTRE_CONFIG
WHERE _ID in (
    SELECT ECC._ID
    FROM ENTITY_CENTRE_CONFIG ECC,
        (SELECT
            CONCAT(MAX(SUBSTRING(TITLE, 1, 15)), '[', SUBSTRING(TITLE, 17, 100)) AS TITLE_TO_DELETE,
            ID_CRAFT,
            ID_MAIN_MENU
        FROM ENTITY_CENTRE_CONFIG
        WHERE
            TITLE LIKE '__________SAVED[[]%'
            OR TITLE LIKE '__________FRESH[[]%'
        GROUP BY
            ID_MAIN_MENU,
            ID_CRAFT,
            SUBSTRING(TITLE, 17, 100)
        HAVING
            COUNT(SUBSTRING(TITLE, 1, 15)) < 2
            AND MAX(SUBSTRING(TITLE, 1, 15)) = '__________SAVED'
        ) SUB
    WHERE
        ECC.TITLE = SUB.TITLE_TO_DELETE
        AND ECC.ID_CRAFT = SUB.ID_CRAFT
        AND ECC.ID_MAIN_MENU = SUB.ID_MAIN_MENU
)

/* DEKTOP: check again after deletion */
SELECT
    CONCAT(MAX(SUBSTRING(TITLE, 1, 15)), '[', SUBSTRING(TITLE, 17, 100)) AS TITLE_TO_DELETE,
    (SELECT KEY_ FROM USER_ U WHERE U._ID = ID_CRAFT) AS OWNER,
    (SELECT KEY_ FROM MAIN_MENU M WHERE M._ID = ID_MAIN_MENU) AS MI_TYPE
FROM ENTITY_CENTRE_CONFIG
WHERE
    TITLE LIKE '__________SAVED[[]%'
    OR TITLE LIKE '__________FRESH[[]%'
GROUP BY
    ID_MAIN_MENU,
    ID_CRAFT,
    SUBSTRING(TITLE, 17, 100)
HAVING
    COUNT(SUBSTRING(TITLE, 1, 15)) < 2
    AND MAX(SUBSTRING(TITLE, 1, 15)) = '__________SAVED'

/* MOBILE: check */
SELECT
  CONCAT(MAX(SUBSTRING(TITLE, 1, 21)), '[', SUBSTRING(TITLE, 23, 100)) AS TITLE_TO_DELETE,
  (SELECT KEY_ FROM USER_ U WHERE U._ID = ID_CRAFT) AS OWNER,
  (SELECT KEY_ FROM MAIN_MENU M WHERE M._ID = ID_MAIN_MENU) AS MI_TYPE
FROM ENTITY_CENTRE_CONFIG
WHERE
  TITLE LIKE 'MOBILE__________SAVED[[]%'
  OR TITLE LIKE 'MOBILE__________FRESH[[]%'
GROUP BY
  ID_MAIN_MENU,
  ID_CRAFT,
  SUBSTRING(TITLE, 23, 100)
HAVING
  COUNT(SUBSTRING(TITLE, 1, 21)) < 2
  AND MAX(SUBSTRING(TITLE, 1, 21)) = 'MOBILE__________SAVED'

/* MOBILE: delete */
DELETE
FROM ENTITY_CENTRE_CONFIG
WHERE _ID in (
    SELECT ECC._ID
    FROM ENTITY_CENTRE_CONFIG ECC,
        (SELECT
            CONCAT(MAX(SUBSTRING(TITLE, 1, 21)), '[', SUBSTRING(TITLE, 23, 100)) AS TITLE_TO_DELETE,
            ID_CRAFT,
            ID_MAIN_MENU
        FROM ENTITY_CENTRE_CONFIG
        WHERE
            TITLE LIKE 'MOBILE__________SAVED[[]%'
            OR TITLE LIKE 'MOBILE__________FRESH[[]%'
        GROUP BY
            ID_MAIN_MENU,
            ID_CRAFT,
            SUBSTRING(TITLE, 23, 100)
        HAVING
            COUNT(SUBSTRING(TITLE, 1, 21)) < 2
            AND MAX(SUBSTRING(TITLE, 1, 21)) = 'MOBILE__________SAVED'
        ) SUB
    WHERE
        ECC.TITLE = SUB.TITLE_TO_DELETE
        AND ECC.ID_CRAFT = SUB.ID_CRAFT
        AND ECC.ID_MAIN_MENU = SUB.ID_MAIN_MENU
)

/* MOBILE: check again after deletion */
SELECT
  CONCAT(MAX(SUBSTRING(TITLE, 1, 21)), '[', SUBSTRING(TITLE, 23, 100)) AS TITLE_TO_DELETE,
  (SELECT KEY_ FROM USER_ U WHERE U._ID = ID_CRAFT) AS OWNER,
  (SELECT KEY_ FROM MAIN_MENU M WHERE M._ID = ID_MAIN_MENU) AS MI_TYPE
FROM ENTITY_CENTRE_CONFIG
WHERE
  TITLE LIKE 'MOBILE__________SAVED[[]%'
  OR TITLE LIKE 'MOBILE__________FRESH[[]%'
GROUP BY
  ID_MAIN_MENU,
  ID_CRAFT,
  SUBSTRING(TITLE, 23, 100)
HAVING
  COUNT(SUBSTRING(TITLE, 1, 21)) < 2
  AND MAX(SUBSTRING(TITLE, 1, 21)) = 'MOBILE__________SAVED'

ROLLBACK TRANSACTION transactio