package ua.com.fielden.platform.entity.annotation;

import ua.com.fielden.platform.domaintree.ICalculatedProperty.CalculatedPropertyAttribute;
import ua.com.fielden.platform.domaintree.ICalculatedProperty.CalculatedPropertyCategory;
import ua.com.fielden.platform.domaintree.IDomainTreeEnhancer;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Specifies that the annotated property is calculated.
///
/// An expression can be specified in one of the following ways:
///
/// 1. In [#value()] using the Expression Language.
///    ```
///    @IsProperty
///    @Calculated("SUM(quantity * price)")
///    Integer total;
///    ```
///
/// 2. In a separate static field using EQL.
///    The static field's name must be equal to the property name with `_` appended.
///    For some component-typed properties, extra expressions can be specified for specific components.
///    The name of a static field for an extra expression must be formed by joining property names with `_` and appending `_` at the end
///    (e.g., `price_currency_` for `price.currency`).
///    Each component types should document whether it supports this functionality.
///    ```
///    @IsProperty
///    @Calculated
///    Integer total;
///    static final ExpressionModel total_ = expr()...model();
///
///    @IsProperty
///    @Calculated
///    Money totalCost;
///    static final ExpressionModel totalCost_ = expr()...model(),
///                                 totalCost_currency_ = expr()...model();
///    ```
///
/// Calculated properties with expressions defined in one of these ways are _non-contextual_.
/// They are expressed in terms of the enclosing entity type.
///
/// There are also _contextual_ properties, which are auto-generated by [IDomainTreeEnhancer] and should not be used explicitly.
/// Only attribute [#value()] should be used in domain modelling.
///
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD })
public @interface Calculated {

    String NOTHING = "-%-> NOTHING <-%-";
    String EMPTY = "";

    /// An Expression Language program that defines the calculated property.
    ///
    String value() default EMPTY;

    /// The root type name.
    ///
    String rootTypeName() default NOTHING;

    /// A path that defines the context of the calculated property.
    /// This path should be fully defined in the context of the root type.
    ///
    String contextPath() default NOTHING;

    /// The attribute of the calculated property.
    ///
    CalculatedPropertyAttribute attribute() default CalculatedPropertyAttribute.NO_ATTR;

    /// The name of the property in the context type, from which this calculated property originates.
    ///
    String origination() default NOTHING;

    /// The category of the calculated property.
    ///
    CalculatedPropertyCategory category() default CalculatedPropertyCategory.EXPRESSION;
}
