package ua.com.fielden.platform.sample.domain;

import ua.com.fielden.platform.data.generator.WithCreatedByUser;
import ua.com.fielden.platform.entity.AbstractPersistentEntity;
import ua.com.fielden.platform.entity.DynamicEntityKey;
import ua.com.fielden.platform.entity.annotation.*;
import ua.com.fielden.platform.security.user.User;
import ua.com.fielden.platform.types.Money;
import ua.com.fielden.platform.types.markers.IMoneyType;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Represents a typical example of an entity to be generated. This particular entity is generated by generator {@link TgGeneratedEntityGenerator}.
 *
 * @author TG Team
 *
 */
@KeyType(DynamicEntityKey.class)
@CompanionObject(ITgGeneratedEntityForTrippleDecAnalysis.class)
@MapEntityTo
@DescTitle("Tripple dec entity description")
public class TgGeneratedEntityForTrippleDecAnalysis extends AbstractPersistentEntity<DynamicEntityKey> implements WithCreatedByUser<TgGeneratedEntityForTrippleDecAnalysis> {

    @IsProperty(assignBeforeSave = true)
    @MapTo
    @Title(value = "User", desc = "User who created this entity instance.")
    @CompositeKeyMember(1)
    private User createdBy;

    @IsProperty(assignBeforeSave = true)
    @MapTo
    @Title(value = "Creation Date", desc = "The date/time when this entity instance was created.")
    @CompositeKeyMember(2)
    private Date createdDate;

    @IsProperty
    @MapTo
    @Title("Group property")
    @CompositeKeyMember(3)
    @Readonly
    private String group;

    @IsProperty
    @MapTo
    @Title("Count")
    private Integer count;

    @IsProperty
    @MapTo
    @Title("Cost")
    @PersistentType(userType = IMoneyType.class)
    private Money cost;

    @IsProperty
    @MapTo
    @Title(value = "Hours", desc = "Desc")
    private BigDecimal hours;

    @IsProperty
    @CritOnly(CritOnly.Type.SINGLE)
    @Title(value = "Entities count", desc = "Desc")
    private Integer entityCount;

    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setEntityCount(final Integer entityCount) {
        this.entityCount = entityCount;
        return this;
    }

    public Integer getEntityCount() {
        return entityCount;
    }

    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setHours(final BigDecimal hours) {
        this.hours = hours;
        return this;
    }

    public BigDecimal getHours() {
        return hours;
    }

    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setCost(final Money cost) {
        this.cost = cost;
        return this;
    }

    public Money getCost() {
        return cost;
    }

    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setCount(final Integer count) {
        this.count = count;
        return this;
    }

    public Integer getCount() {
        return count;
    }

    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setGroup(final String group) {
        this.group = group;
        return this;
    }

    public String getGroup() {
        return group;
    }

    @Override
    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setCreatedBy(final User createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public User getCreatedBy() {
        return createdBy;
    }

    @Override
    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setCreatedDate(final Date creationTime) {
        createdDate = creationTime;
        return this;
    }

    @Override
    public Date getCreatedDate() {
        return createdDate;
    }

    @Override
    @Observable
    public TgGeneratedEntityForTrippleDecAnalysis setDesc(final String desc) {
        super.setDesc(desc);
        return this;
    }
}