package ua.com.fielden.platform.sample.domain;

import ua.com.fielden.platform.data.generator.WithCreatedByUser;
import ua.com.fielden.platform.entity.AbstractEntity;
import ua.com.fielden.platform.entity.DynamicEntityKey;
import ua.com.fielden.platform.entity.annotation.*;
import ua.com.fielden.platform.entity.annotation.CritOnly.Type;
import ua.com.fielden.platform.reflection.TitlesDescsGetter;
import ua.com.fielden.platform.security.user.User;
import ua.com.fielden.platform.utils.Pair;

import static ua.com.fielden.platform.entity.annotation.CritOnly.Type.SINGLE;

/// Represents a typical example of an entity to be generated. This particular entity is generated by generator `TgGeneratedEntityGenerator`.
///
@KeyType(DynamicEntityKey.class)
@CompanionObject(ITgGeneratedEntity.class)
@MapEntityTo
@DescTitle("Desc")
public class TgGeneratedEntity extends AbstractEntity<DynamicEntityKey> implements WithCreatedByUser<TgGeneratedEntity> {

    private static final Pair<String, String> entityTitleAndDesc = TitlesDescsGetter.getEntityTitleAndDesc(TgGeneratedEntity.class);
    public static final String ENTITY_TITLE = entityTitleAndDesc.getKey();
    public static final String ENTITY_DESC = entityTitleAndDesc.getValue();

    @IsProperty(assignBeforeSave = true)
    @MapTo
    @Title(value = "User", desc = "User who created this entity instance.")
    @CompositeKeyMember(1)
    private User createdBy;

    @IsProperty
    @MapTo
    @Title(value = "Entity Key", desc = "Unique within a generated batch.")
    @CompositeKeyMember(2)
    private String entityKey;

    @IsProperty
    @CritOnly(Type.MULTI)
    @Title(value = "CritOnly Multi", desc = "CritOnly multi property")
    private User critOnlyMultiProp;

    @IsProperty
    @CritOnly(SINGLE)
    @Title(value = "CritOnly Single", desc = "CritOnly single property")
    private User critOnlySingleProp;

    @IsProperty
    @CritOnly(SINGLE)
    @Required
    private Integer requiredProp;

    public Integer getRequiredProp() {
        return requiredProp;
    }

    @Observable
    public TgGeneratedEntity setRequiredProp(Integer requiredProp) {
        this.requiredProp = requiredProp;
        return this;
    }

    @Observable
    public TgGeneratedEntity setEntityKey(final String entityKey) {
        this.entityKey = entityKey;
        return this;
    }

    public String getEntityKey() {
        return entityKey;
    }

    @Observable
    public TgGeneratedEntity setCreatedBy(final User createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    @Observable
    public TgGeneratedEntity setCritOnlySingleProp(final User critOnlySingleProp) {
        this.critOnlySingleProp = critOnlySingleProp;
        return this;
    }

    public User getCritOnlySingleProp() {
        return critOnlyMultiProp;
    }

    @Observable
    public TgGeneratedEntity setCritOnlyMultiProp(final User critOnlyMultiProp) {
        this.critOnlyMultiProp = critOnlyMultiProp;
        return this;
    }

    public User getCritOnlyMultiProp() {
        return critOnlyMultiProp;
    }
}